### ISSUE TITLE
How is your WMT16 EN-Ro Dataset Preprocessed?

### ISSUE THREAD

**Issue by ictnlp-wshugen** [nyu-dl/dl4mt-nonauto#10]
Thank you for providing us the preprocessed dataset.
Could do please tell me How is your WMT16 EN-Ro Dataset Preprocessed?
From raw 612422 sentence pairs to 608319 sentence pairs?
Also, it seems that the dataset (En-Ro) has been shuffled or reorganized?

**Comment by jaseleephd** [comment]
We used the preprocessing [scripts](https://github.com/rsennrich/wmt16-scripts/tree/master/sample) provided by Rico Sennrich, which filters out sentences too long or too short.
