### ISSUE TITLE
I receive Error for "model.py" 

### ISSUE THREAD

**Issue by VahidChahkandi** [nyu-dl/dl4mt-nonauto#11]
Hi, first of all, thank you for sharing your code.
could you please advise what I have to do when receiving this error when one class called "model.py".

line 265, in <module>
args.block_cls = model.HighwayBlock
NameError: name 'model' is not defined

Thank you in advance.

**Comment by mansimov** [comment]
Hi,
It sounds like an error importing the class.
Did you make sure that you have imported `model.py` ?

**Comment by VahidChahkandi** [comment]
Yes, I'm sure and that makes me surprised! 
"model.py" is a python file contain `HighwayBlock` class and some other classes and I put that in the same folder that `run.py` is, but the error says there is no `model.py` file.
Those lines that cause of this error is as follows:

`if args.ffw_block == "nonresidual":
    args.block_cls = model.NonresidualBlock
elif args.ffw_block == "residual":
    args.block_cls = model.ResidualBlock
elif args.ffw_block == "highway":
    args.block_cls = model.HighwayBlock`

> Hi,
> It sounds like an error importing the class.
> Did you make sure that you have imported `model.py` ?
