### ISSUE TITLE
Test data for reproducing IWSLT-16 En-De results

### ISSUE THREAD

**Issue by butsugiri** [nyu-dl/dl4mt-nonauto#5]
I am trying to reproduce the results of IWSLT-16 En-De experiment, using pretrained models.
I got the dataset from the link written in README (https://drive.google.com/file/d/1m7dZqEXHWPYcre6xxsFwFLrb9CRCZGmn/view?usp=sharing)

I want to apply the test data, but the bpe-version of the data is not available in the directory.
(there are `valid.en-de.bpe.de, valid.en-de.bpe.en` for validation data, but not for test data)

Can you share them?

**Comment by mansimov** [comment]
@jasonleeinf

**Comment by baoy-nlp** [comment]
> I am trying to reproduce the results of IWSLT-16 En-De experiment, using pretrained models.
> I got the dataset from the link written in README (https://drive.google.com/file/d/1m7dZqEXHWPYcre6xxsFwFLrb9CRCZGmn/view?usp=sharing)
> 
> I want to apply the test data, but the bpe-version of the data is not available in the directory.
> (there are `valid.en-de.bpe.de, valid.en-de.bpe.en` for validation data, but not for test data)
> 
> Can you share them?

The paper does not report the result on test data of IWSLT EN-DE. You may not need to reproduce it.
