### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for FastTransformer:

### ISSUE THREAD

**Issue by mohengzxr** [nyu-dl/dl4mt-nonauto#6]
size mismatch for encoder.out.weight: copying a param with shape torch.Size([36377, 278]) from checkpoint, the shape in current model is torch.Size([38022, 278]).
	size mismatch for decoder.0.out.weight: copying a param with shape torch.Size([36377, 278]) from checkpoint, the shape in current model is torch.Size([38022, 278]).
	size mismatch for decoder.1.out.weight: copying a param with shape torch.Size([36377, 278]) from checkpoint, the shape in current model is torch.Size([38022, 278]).

**Comment by mohengzxr** [comment]
Decoding from NA Models   why?   --load_vocab,Why does it appear size mismatch for encoder.out.weight: copying a param with shape torch.Size([36377, 278]) from checkpoint, the shape in current model is torch.Size([38022, 278]).???

**Comment by mohengzxr** [comment]
@mansimov

**Comment by mansimov** [comment]
Hm it is a bit hard for me to figure out why this happens.
Haven't used this codebase for about a year or so...

**Comment by mohengzxr** [comment]
--lr_schedule   anneal and transformer different?
@

**Comment by mohengzxr** [comment]
@mansimov

**Comment by mansimov** [comment]
--lr_schedule anneal just anneals the learning rate starting from certain value
--lr_schedule transformer first warmups up the learning rate and then anneals it down. by warming up I mean it increases the learning rate from very low value to certain value like 3e-4 for first couple of training iterations. see original transformer paper for reference

**Comment by mohengzxr** [comment]
anneal and transformer  ?Whether it affects Bleu?
@mansimov

**Comment by mohengzxr** [comment]
Why is the Bleu produced by choosing ananne and transformer different? 
What is their impact on bleu?
Thank you 
@mansimov

**Comment by mansimov** [comment]
Anneal works for well for IWSLT, transformer works well for WMT.
In general I advice to use transformer schedule. 
Don't remember how exact impact of choosing learning rate schedules is on bleu

**Comment by mohengzxr** [comment]
In the experiment, we chose the Uyghur-Chinese corpus. 
When using ananne and transformer, the Bleu of the two is very different.
I don't understand very much.

**Comment by mohengzxr** [comment]
I am very interested in this paper, I want to have a little research on your basis.

**Comment by mohengzxr** [comment]
I really hope to get your help.

**Comment by mansimov** [comment]
I am glad that you are interested :)

It is very hard to say why results are different without diving into details. But it is unsurprising to me that with Transformers you need to be careful with learning rate schedule depending on number of GPUs you have, model size and dataset size!

Good luck!

**Comment by mohengzxr** [comment]
@jasonleeinf @mansimov @kyunghyuncho 
Hi 
In your paper, 
Equation 2: t=1,l=0,l-1=-1 is wrong;
Excuse me, how did you explain it? I hope to help you.

![image](https://user-images.githubusercontent.com/38642026/71763799-16b7fb00-2f1b-11ea-997f-1f4181321720.png)

**Comment by mohengzxr** [comment]
![image](https://user-images.githubusercontent.com/38642026/71763805-259ead80-2f1b-11ea-9c0c-3787f7fec3b5.png)

**Comment by mansimov** [comment]
Hi @mohengzxr 

Thanks for pointing out this mistake in the paper. l=1 instead of l=0 in the first sum.
Best, Elman
