### ISSUE TITLE
IWSLT-16 En-De Decoding 

### ISSUE THREAD

**Issue by wesleyjtann** [nyu-dl/dl4mt-nonauto#8]
Hi, I have been trying to reproduce the validation results of IWSLT-16 En-De experiments using the pre-trained models. However, I'm getting the following results for the AR model:

UserWarning: 
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()

iter 1 | BLEU = 0.00, 3.4/0.2/0.0/0.0 (BP=1.000, ratio=2.090, hyp_len=41421, ref_len=19823)

For the AR model, I'm running:
```
python run.py --dataset iwslt-ende --vocab_size 40000 --ffw_block highway --params small --lr_schedule anneal --batch_size 1024 --mode test --debug --gpu 0 --load_vocab --load_from ~/nlp/dl4mt-nonauto/models/iwslt16/ende/02.05_23.12.ar_voc40k_2048_5_278_507_2_drop_0.1_0.0003_tran_high_
```

For the NAT model, I'm running:
```
python run.py --dataset iwslt-ende --vocab_size 40000 --ffw_block highway --params small --lr_schedule anneal --batch_size 128 --fast --valid_repeat_dec 20 --use_argmax --next_dec_input both --mode test --remove_repeats --debug --gpu 0 --load_vocab --trg_len_option predict --use_predicted_trg_len --load_from ~/nlp/dl4mt-nonauto/models/iwslt16/ende/02.08_20.10.ptrn_model_voc40k_2048_5_278_507_2_drop_0.1_drop_len_pred_0.3_0.0003_anne_anneal_steps_250000_high_tr4_2decs__pred_both_copy_argmax_
```

May I know what are the correct flags to set? Thanks!

**Comment by jaseleephd** [comment]
Sorry about the delay.

Have you manually inspected the output to see if there's any obvious errors (e.g. provided vocab is wrong)? Also are you getting 0 BLEU for both autoregressive and non-autoregressive models?
